ric_calendar/config/routes.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Routes
# *
# * Author:
# * Date  : 21. 2. 2017
# *
# *****************************************************************************

RicCalendar::Engine.routes.draw do

	# Calendars
	resources :calendars, except: [:show] do
		collection do
			get  "export"
			get  "events"
			post "events"
			get  "resources"
			post "resources"
		end

		# iCalendar output
		resources :icals, only: [:show]
	end

	# Events
	resources :events, except: [:index]
end

ric_calendar/app/models/ric_calendar/calendar.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Calendar
# *
# * Author: Jaroslav Mlejnek
# * Date  : 19. 2. 2017
# *
# *****************************************************************************

module RicCalendar
	class Calendar < ActiveRecord::Base
		# include RicCalendar::Concerns::Models::Validity
		include RicCalendar::Concerns::Models::Colored
		include RicCalendar::Concerns::Models::Calendar
	end
end

ric_calendar/app/models/ric_calendar/calendar_event.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Document model
# *
# * Author:
# * Date  : 19. 2. 2017
# *
# *****************************************************************************

module RicCalendar
	class CalendarEvent < ActiveRecord::Base
		include RicCalendar::Concerns::Models::Schedulable
		include RicCalendar::Concerns::Models::Recurring

		include RicCalendar::Concerns::Models::CalendarEvent
	end
end

ric_calendar/app/models/ric_calendar/event.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Event
# *
# * Author: Jaroslav Mlejnek
# * Date  : 19. 2. 2017
# *
# *****************************************************************************

module RicCalendar
	class Event < ActiveRecord::Base
		include RicCalendar::Concerns::Models::Schedulable
		include RicCalendar::Concerns::Models::Recurring
		include RicCalendar::Concerns::Models::Validity
		include RicCalendar::Concerns::Models::Colored
		include RicCalendar::Concerns::Models::Event
	end
end

ric_calendar/app/controllers/ric_calendar/application_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Abstract engine controller
# *
# * Author: Matěj Outlý
# * Date  : 19. 2. 2017
# *
# *****************************************************************************

module RicCalendar
	class ApplicationController < ::ApplicationController
		include RicCalendar::Concerns::Authorization
	end
end

ric_calendar/app/controllers/ric_calendar/calendar_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Document Folders
# *
# * Author:
# * Date  : 21. 2. 2017
# *
# *****************************************************************************

require_dependency "ric_calendar/application_controller"

module RicCalendar
	class CalendarController < ApplicationController
		include RicCalendar::Concerns::Controllers::CalendarController
	end
end

ric_calendar/app/controllers/ric_calendar/calendar_event_templates_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Document Folders
# *
# * Author:
# * Date  : 21. 2. 2017
# *
# *****************************************************************************

require_dependency "ric_calendar/application_controller"

module RicCalendar
	class CalendarEventTemplatesController < ApplicationController
		include RicCalendar::Concerns::Controllers::CalendarEventTemplatesController
	end
end

ric_calendar/app/controllers/ric_calendar/calendar_events_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Document Folders
# *
# * Author:
# * Date  : 21. 2. 2017
# *
# *****************************************************************************

require_dependency "ric_calendar/application_controller"

module RicCalendar
	class CalendarEventsController < ApplicationController
		include RicCalendar::Concerns::Controllers::CalendarEventsController
		include RicCalendar::Concerns::Controllers::UpdateScheduleAction
	end
end

ric_calendar/app/controllers/ric_calendar/calendars_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Calendars
# *
# * Author:
# * Date  : 21. 2. 2017
# *
# *****************************************************************************

require_dependency "ric_calendar/application_controller"

module RicCalendar
	class CalendarsController < ApplicationController
		include RicCalendar::Concerns::Controllers::CalendarsController
	end
end

ric_calendar/app/controllers/ric_calendar/events_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Events
# *
# * Author:
# * Date  : 21. 2. 2017
# *
# *****************************************************************************

require_dependency "ric_calendar/application_controller"

module RicCalendar
	class EventsController < ApplicationController
		include RicCalendar::Concerns::Controllers::EventsController
	end
end

ric_calendar/app/controllers/ric_calendar/ical_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Events
# *
# * Author:
# * Date  : 21. 2. 2017
# *
# *****************************************************************************

require_dependency "ric_calendar/application_controller"

module RicCalendar
	class IcalController < ApplicationController
		include RicCalendar::Concerns::Controllers::IcalController
	end
end

ric_calendar/app/controllers/ric_calendar/icals_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Events
# *
# * Author:
# * Date  : 21. 2. 2017
# *
# *****************************************************************************

require_dependency "ric_calendar/application_controller"

module RicCalendar
	class IcalsController < ApplicationController
		include RicCalendar::Concerns::Controllers::IcalsController
	end
end

ric_calendar/app/views/ric_calendar/calendars/_actions.html.erb
<% if can_read_and_write? %>
	<%= rug_menu_for(@calendar, options.merge(path_base: "calendars")) do |m| %>
		<%= m.item t("headers.ric_calendar.calendars.index"), ric_calendar.calendars_path, icon: "calendar", active: (controller_name == "calendars" && action_name == "index") %>
		<%= m.item t("headers.ric_calendar.calendars.export"), ric_calendar.export_calendars_path, icon: "paperclip", active: (controller_name == "calendars" && action_name == "export") %>
		<%= m.new_item %>
		<%= m.edit_item %>
		<%= m.destroy_item %>
	<% end %>
<% end %>

ric_calendar/app/views/ric_calendar/calendars/_form.html.erb
<%= rug_form_for(@calendar, 
	create_path: "ric_calendar.calendars_path", 
	update_path: "ric_calendar.calendar_path") do |f| 
%>
	<%= f.text_input_row :name, :text_field %>
	<%= f.checkbox_row :is_public %>
	<%= f.picker_row :color %>
	<div class="row">
		<div class="col-md-6">
			<%= f.picker_row :kind %>
		</div>
		<div class="col-md-6">
			<%= f.token_input_row :resource_id, resources_calendars_path, as: :resource, limit: 1 %>
		</div>
	</div>
	<%= f.primary_button_row :submit %>
	<%= f.back_link_button_row %>
<% end %>

ric_calendar/app/views/ric_calendar/calendars/_related.html.erb
<% if action_name == "index" %>
	<ul class="actions-list">
		<% @calendars.each do |calendar| %>
			<li style="background: <%= calendar.color_primary %>; color: <%= calendar.color_text %>;">
				<div>
					<label style="margin: 0;">
						<input type="checkbox" data-calendar-id="<%= calendar.id %>" class="toggle-calendar">
						<%= calendar.name %>
					</label>

					<div class="float-right">
						<%= rug_button(rug_icon("pencil"), ric_calendar.edit_calendar_path(calendar), style: "primary", size: "xs") if can_read_and_write? %>
						<%= rug_button(rug_icon("trash"), ric_calendar.calendar_path(calendar), method: "delete", style: "danger", size: "xs") if can_read_and_write? %>
					</div>
				</div>
			</li>
		<% end %>
	</ul>
<% end %>

ric_calendar/app/views/ric_calendar/calendars/export.html.erb
<div class="callout callout-info">
	<%= t("general.ical_import") %>
</div>

<% 
	columns = rug_columns
	columns.add_column_by_type(:name, :string)
	columns.add_column_by_block(:ical_url) do |calendar|
		url = calendar_ical_url(calendar, current_user)
		link_to(url, url)
	end
%>
<%= rug_index_table_for(@calendars, columns) %>

ric_calendar/app/views/ric_calendar/calendars/index.html.erb
<% content_for :page_header, "false" %>
<% hash = "1" %>
<script>
	var ric_calendar_<%= hash %> = null;
	$(document).ready(function() {
		ric_calendar_<%= hash %> = new RicCalendar('<%= hash %>', {
			url: '<%= events_calendars_path %>',
			newUrl: '<%= can_read_and_write? ? new_event_path : "" %>',
			toggleCalendarSelector: '.toggle-calendar',
		});
		ric_calendar_<%= hash %>.ready();
	});
</script>
<div class="ric-calendar" id="ric-calendar-<%= hash %>"></div>