ric_dms/config/routes.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Routes
# *
# * Author:
# * Date  : 21. 2. 2017
# *
# *****************************************************************************

RicDms::Engine.routes.draw do

	# Folders
	resources :folders, only: [:index, :show, :new, :edit, :create, :update, :destroy] do

		# Documents
		resources :documents, only: [:show, :new, :edit, :create, :update, :destroy] do

			# Document versions
			resources :versions, only: [:destroy]

		end

	end	

end

ric_dms/app/models/ric_dms/document.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Document model
# *
# * Author: Jaroslav Mlejnek
# * Date  : 19. 2. 2017
# *
# *****************************************************************************

module RicDms
	class Document < ActiveRecord::Base
		include RicDms::Concerns::Models::Document
	end
end

ric_dms/app/models/ric_dms/document_folder.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Document folder model
# *
# * Author: Jaroslav Mlejnek
# * Date  : 19. 2. 2017
# *
# *****************************************************************************

module RicDms
	class DocumentFolder < ActiveRecord::Base
		include RicDms::Concerns::Models::DocumentFolder
	end
end

ric_dms/app/models/ric_dms/document_version.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Document version model
# *
# * Author: Jaroslav Mlejnek
# * Date  : 19. 2. 2017
# *
# *****************************************************************************

module RicDms
	class DocumentVersion < ActiveRecord::Base
		include RicDms::Concerns::Models::DocumentVersion
	end
end

ric_dms/app/controllers/ric_dms/application_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Abstract engine controller
# *
# * Author: Matěj Outlý
# * Date  : 19. 2. 2017
# *
# *****************************************************************************

module RicDms
	class ApplicationController < ::ApplicationController
		include RicDms::Concerns::Authorization
	end
end

ric_dms/app/controllers/ric_dms/document_folders_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Document Folders
# *
# * Author:
# * Date  : 21. 2. 2017
# *
# *****************************************************************************

require_dependency "ric_dms/application_controller"

module RicDms
	class DocumentFoldersController < ApplicationController
		include RicDms::Concerns::Controllers::DocumentFoldersController
	end
end

ric_dms/app/controllers/ric_dms/document_versions_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Document Versions
# *
# * Author:
# * Date  : 21. 2. 2017
# *
# *****************************************************************************

require_dependency "ric_dms/application_controller"

module RicDms
	class DocumentVersionsController < ApplicationController
		include RicDms::Concerns::Controllers::DocumentVersionsController
	end
end

ric_dms/app/controllers/ric_dms/documents_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Documents
# *
# * Author: Matěj Outlý
# * Date  : 21. 2. 2017
# *
# *****************************************************************************

require_dependency "ric_dms/application_controller"

module RicDms
	class DocumentsController < ApplicationController
		include RicDms::Concerns::Controllers::DocumentsController
	end
end

ric_dms/app/controllers/ric_dms/folders_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Document Folders
# *
# * Author: Matěj Outlý
# * Date  : 21. 2. 2017
# *
# *****************************************************************************

require_dependency "ric_dms/application_controller"

module RicDms
	class FoldersController < ApplicationController
		include RicDms::Concerns::Controllers::FoldersController
	end
end

ric_dms/app/controllers/ric_dms/versions_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Document Versions
# *
# * Author: Matěj Outlý
# * Date  : 21. 2. 2017
# *
# *****************************************************************************

require_dependency "ric_dms/application_controller"

module RicDms
	class VersionsController < ApplicationController
		include RicDms::Concerns::Controllers::VersionsController
	end
end

ric_dms/app/views/ric_dms/folders/_actions.html.erb
<%= rug_menu_for(@document_folder, options.merge(path_base: "folder")) do |m| %>
	<%= m.edit_item if can_update? %>
	<%= m.destroy_item if can_destroy? %>
<% end %>

ric_dms/app/views/ric_dms/folders/_form.html.erb
<%= rug_form_for(@document_folder, 
	create_path: :folders_path,
	update_path: :folder_path
) do |f| %>
	<div class="row">
		<div class="col-sm-6">
			<div class="form-group">
				<%= f.label_for :parent_id %>
				<%= f.select :parent_id, nested_set_options(@root_folder ? @root_folder : RicDms::DocumentFolder, @document_folder) {|i| "#{'-' * i.level} #{i.name}" }, { include_blank: @root_folder ? false : "(není)" }, { class: "form-control" } %>
				<%= f.errors :parent_id %>
			</div>
		</div>
		<div class="col-sm-6">
			<%= f.text_input_row :name %>
		</div>
	</div>
	<%= f.text_area_row :description %>
	<%= f.primary_button_row :submit %>
	<%= f.back_link_button_row %>
<% end %>

ric_dms/app/views/ric_dms/folders/edit.html.erb
<div class="form-box">
	<%= render partial: "form" %>
</div>

ric_dms/app/views/ric_dms/folders/index.html.erb
<div class="form-box p-b-sm document-listing">
	<%= render partial: "ric_dms/partials/listing_folders" %>
	<%= render partial: "ric_dms/partials/listing_files" if @document_folder %>
</div>

ric_dms/app/views/ric_dms/partials/_listing_file.html.erb
<%= link_to document.current_version.attachment.url, "data-document-id" => document.id do %>
	<span class="document-mime-type">
		<i class="fas <%= mime_type_fa_icon(document.current_version.attachment_content_type) %> fa-3x"></i>
	</span>
	<span class="document-name">
		<%= document.name.to_s.gsub("_", " ") %>
	</span>
<% end %>

ric_dms/app/views/ric_dms/partials/_listing_files.html.erb
<div class="document-listing-files">

	<% @documents.each do |document| %>
		<div class="document-file" data-mh="document">
			<%= render partial: "ric_dms/partials/listing_file", locals: { document: document } %>
			<div class="document-actions">
				<%= link_to rug_icon(:show), folder_document_path(@document_folder, document) if can_load? %>
				<%= link_to rug_icon(:edit), edit_folder_document_path(@document_folder, document) if can_update? %>
				<%= link_to rug_icon(:destroy), folder_document_path(@document_folder, document), method: :delete, data: { confirm: t("general.are_you_sure") } if can_destroy? %>
			</div>
		</div>
	<% end %>

	<% if can_create? %>
		<div class="document-file document-new" data-mh="document">
			<%= link_to new_folder_document_path(folder_id: @document_folder) do %>
				<span class="document-mime-type">
					<i class="fas fa-file fa-3x"></i>
				</span>
				<span class="document-name">
					<%= t("headers.ric_dms.documents.new") %>
				</span>
			<% end %>
		</div>
	<% end %>

</div>

ric_dms/app/views/ric_dms/partials/_listing_folders.html.erb
<div class="document-listing-folders">

	<% @document_folders.each do |document_folder| %>
		<div class="document-folder" data-mh="document">
			<%= link_to folder_path(document_folder), "data-document-folder-id" => document_folder.id do %>
				<span class="document-mime-type">
					<i class="fas fa-folder fa-3x"></i>
				</span>
				<span class="document-name">
					<%= document_folder.name.to_s.gsub("_", " ") %>
				</span>
			<% end %>
			<div class="document-actions">
				<%= link_to rug_icon(:edit), edit_folder_path(document_folder) if can_update? %>
				<%= link_to rug_icon(:destroy), folder_path(document_folder), method: :delete, data: { confirm: t("general.are_you_sure") } if can_destroy? %>
			</div>
		</div>
	<% end %>

	<% if can_create? %>
		<div class="document-folder document-new" data-mh="document">
			<%= link_to new_folder_path(folder_id: @document_folder) do %>
				<span class="document-mime-type">
					<i class="fas fa-folder fa-3x"></i>
				</span>
				<span class="document-name">
					<%= t("headers.ric_dms.folders.new") %>
				</span>
			<% end %>
		</div>
	<% end %>

</div>