ric_settings/config/routes.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Routes
# *
# * Author: Matěj Outlý
# * Date  : 13. 5. 2015
# *
# *****************************************************************************

RicSettings::Engine.routes.draw do

	# Settings
	resource :settings, only: [:show, :edit, :update]
	
end

ric_settings/app/models/ric_settings/setting.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Setting
# *
# * Author: Matěj Outlý
# * Date  : 7. 10. 2015
# *
# *****************************************************************************

module RicSettings
	class Setting < ActiveRecord::Base
		include RicSettings::Concerns::Models::Setting
	end
end

ric_settings/app/models/ric_settings/settings_collection.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Settings collection
# *
# * Author: Matěj Outlý
# * Date  : 7. 10. 2015
# *
# *****************************************************************************

module RicSettings
	class SettingsCollection
		include ActiveModel::Model
		include RicSettings::Concerns::Models::SettingsCollection

		#
		# Define available settings
		#
		#setting "setting1", :string, "category1"
		#setting "setting2", :integer, "category1"
		#setting "setting3", :enum, "category3", values: ["value1", "value2", "value3"]

	end
end

ric_settings/app/controllers/ric_settings/admin_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Abstract engine controller
# *
# * Author: Matěj Outlý
# * Date  : 13. 5. 2015
# *
# *****************************************************************************

module RicSettings
	class AdminController < RuthAdmin::ApplicationController
	end
end

ric_settings/app/controllers/ric_settings/admin_settings_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Settings
# *
# * Author: Matěj Outlý
# * Date  : 7. 10. 2015
# *
# *****************************************************************************

require_dependency "ric_settings/admin_controller"

module RicSettings
	class AdminSettingsController < AdminController
		include RicSettings::Concerns::Controllers::Admin::SettingsController
	end
end

ric_settings/app/controllers/ric_settings/application_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Abstract engine controller
# *
# * Author: Matěj Outlý
# * Date  : 13. 5. 2015
# *
# *****************************************************************************

module RicSettings
	class ApplicationController < ::ApplicationController
	end
end

ric_settings/app/controllers/ric_settings/settings_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Settings
# *
# * Author: Matěj Outlý
# * Date  : 7. 10. 2015
# *
# *****************************************************************************

require_dependency "ric_settings/application_controller"

module RicSettings
	class SettingsController < ApplicationController
		include RicSettings::Concerns::Controllers::SettingsController
	end
end

ric_settings/app/views/ric_settings/settings/_actions.html.erb
<%= rug_menu(options) do |m| %>
	<%= m.item t("headers.ric_settings.settings.show"), :settings, icon: "cog", active: (action_name == "show") %>
	<%= m.item t("headers.ric_settings.settings.edit"), :edit_settings, icon: :edit, active: (action_name == "edit" || action_name == "update") %>
<% end %>

ric_settings/app/views/ric_settings/settings/edit.html.erb
<%= rug_form_for(@settings_collection, url: settings_path, method: :put) do |f| %>
	<%= rug_tabs(RicSettings.theme.tabs_options) do |t| %>
		<% @settings_collection.categories.each_with_index do |(category, settings), index| %>
			<% t.tab category.to_sym, t("activerecord.attributes.ric_settings/settings_collection.category_values.#{category}") do %>
				<% settings.each do |setting_ref| %>
					<%= f.generic_row setting_ref, @settings_collection.settings[setting_ref.to_sym][:kind], label: t("activerecord.attributes.ric_settings/settings_collection.#{setting_ref}") %>
				<% end %>
			<% end %>
		<% end %>
	<% end %>
	<%= f.primary_button_row :submit, label: t("helpers.submit.update") %>
	<%= f.back_link_button_row %>
<% end %>

ric_settings/app/views/ric_settings/settings/show.html.erb
<%= rug_tabs(RicSettings.theme.tabs_options) do |t| %>
	<% @settings_collection.categories.each_with_index do |(category, settings), index| %>
		<% t.tab category.to_sym, t("activerecord.attributes.ric_settings/settings_collection.category_values.#{category}") do %>
			<%= rug_show(@settings_collection) do |t| %>
				<%= t.body do |b| %>
					<% settings.each do |setting_ref| %>
						<%= b.send(@settings_collection.settings[setting_ref.to_sym][:kind], setting_ref, label: t("activerecord.attributes.ric_settings/settings_collection.#{setting_ref}")) %>
					<% end %>
				<% end %>
			<% end %>
		<% end %>
	<% end %>
<% end %>