ric_user/config/routes.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Routes
# *
# * Author: Matěj Outlý
# * Date  : 26. 11. 2015
# *
# *****************************************************************************

RicUser::Engine.routes.draw do

	# Roles
	resources :roles, only: [:index, :create, :update, :destroy] do
		collection do
			post :filter
			get :search
		end
	end

	# Users
	resources :users, only: [:index, :show, :create, :update, :destroy] do
		collection do
			post :filter
			get :search
		end
		member do
			get :lock
			put :lock
			get :unlock
			put :unlock
			get :confirm
			put :confirm
		end

		# User passwords
		resource :password, controller: :user_passwords, only: [:update] do
			member do
				get :regenerate
				put :regenerate
			end
		end

	end

	# Session
	resource :session, only: [:show, :edit, :update]

end

ric_user/app/models/ric_user/people_selector.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * People selector
# *
# * Author: Matěj Outlý
# * Date  : 11. 4. 2017
# *
# *****************************************************************************

module RicUser
	class PeopleSelector < ActiveRecord::Base
		include RicUser::Concerns::Models::PeopleSelector

		# Define selector
#		define_selector :selector_ref, {
#
#			# Select function - DB query selecting valid people expected to be returned
#			select: lambda { |params|
#				SomePerson.where(some_param: params[:some_param])
#			},
#			
#			# Search function - [ {some_param: value, ...}, {some_param: value, ...}, ... ] defining valid selector params expected to be returned
#			search: lambda { |query|
#				SomePerson.where("(lower(unaccent(name_lastname)) LIKE ('%' || lower(unaccent(trim(:query))) || '%'))", query: query).map { |person| { some_param: person.some_param } }
#			},
#			
#			# Selector title - title uniquely identifying selector with given params expected to be returned
#			title: lambda { |params|
#				"Some title for #{SomePerson.find_by(some_param: params[:some_param])}"
#			}
#
#		}

	end
end

ric_user/app/models/ric_user/role.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Role
# *
# * Author: Matěj Outlý
# * Date  : 26. 11. 2015
# *
# *****************************************************************************

module RicUser
	class Role < ActiveRecord::Base
		include RicUser::Concerns::Models::Role
	end
end

ric_user/app/models/ric_user/session.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Session
# *
# * Author: Matěj Outlý
# * Date  : 26. 11. 2015
# *
# *****************************************************************************

module RicUser
	class Session < ActiveRecord::Base
		include RicUser::Concerns::Models::Session
	end
end

ric_user/app/models/ric_user/user.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * User
# *
# * Author: Matěj Outlý
# * Date  : 9. 6. 2015
# *
# *****************************************************************************

module RicUser
	class User < ActiveRecord::Base
		include RicUser::Concerns::Models::User

		# *********************************************************************
		# Authentication
		# *********************************************************************

		if !(defined?(RicAuth).nil?)
			if RicAuth.use_devise
				include RicAuth::Concerns::Models::Devisable
			end
			if RicAuth.use_omniauth
				include RicAuth::Concerns::Models::Omniauthable
			end
		end
		
		# *********************************************************************
		# Roles
		# *********************************************************************
		
		if RicUser.user_role_association == :user_belongs_to_role
			if RicUser.use_static_roles
				include RicUser::Concerns::Models::User::SingleStaticRole
			else
				include RicUser::Concerns::Models::User::SingleDynamicRole
			end
		
		elsif RicUser.user_role_association == :user_has_and_belongs_to_many_roles
			if RicUser.use_static_roles
				include RicUser::Concerns::Models::User::MultiStaticRoles
			else
				include RicUser::Concerns::Models::User::MultiDynamicRoles
			end
		end

	end
end

ric_user/app/models/ric_user/user_person.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * User person
# *
# * Author: Matěj Outlý
# * Date  : 20. 3. 2017
# *
# *****************************************************************************

module RicUser
	class UserPerson < ActiveRecord::Base
		include RicUser::Concerns::Models::UserPerson
	end
end

ric_user/app/models/ric_user/user_role.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * User role
# *
# * Author: Matěj Outlý
# * Date  : 20. 3. 2017
# *
# *****************************************************************************

module RicUser
	class UserRole < ActiveRecord::Base
		include RicUser::Concerns::Models::UserRole
	end
end

ric_user/app/controllers/ric_user/admin_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Abstract engine controller
# *
# * Author: Matěj Outlý
# * Date  : 9. 6. 2015
# *
# *****************************************************************************

module RicUser
	class AdminController < RuthAdmin::ApplicationController
	end
end

ric_user/app/controllers/ric_user/admin_people_selectors_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * People selectors
# *
# * Author: Matěj Outlý
# * Date  : 11. 4. 2017
# *
# *****************************************************************************

require_dependency "ric_user/admin_controller"

module RicUser
	class AdminPeopleSelectorsController < AdminController
		include RicUser::Concerns::Controllers::Admin::PeopleSelectorsController
	end
end

ric_user/app/controllers/ric_user/admin_users_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Users
# *
# * Author: Matěj Outlý
# * Date  : 9. 6. 2015
# *
# *****************************************************************************

require_dependency "ric_user/admin_controller"

module RicUser
	class AdminUsersController < AdminController
		include RicUser::Concerns::Controllers::Admin::UsersController
	end
end

ric_user/app/controllers/ric_user/application_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Abstract engine controller
# *
# * Author: Matěj Outlý
# * Date  : 9. 6. 2015
# *
# *****************************************************************************

module RicUser
	class ApplicationController < ::ApplicationController
	end
end

ric_user/app/controllers/ric_user/people_selectors_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * People selectors
# *
# * Author: Matěj Outlý
# * Date  : 11. 4. 2017
# *
# *****************************************************************************

require_dependency "ric_user/application_controller"

module RicUser
	class PeopleSelectorsController < ApplicationController
		include RicUser::Concerns::Controllers::PeopleSelectorsController
	end
end

ric_user/app/controllers/ric_user/public_session_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Session
# *
# * Author: Matěj Outlý
# * Date  : 26. 11. 2015
# *
# *****************************************************************************

require_dependency "ric_user/public_controller"

module RicUser
	class PublicSessionController < PublicController
		include RicUser::Concerns::Controllers::Public::SessionController
	end
end

ric_user/app/controllers/ric_user/public_users_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Users
# *
# * Author: Matěj Outlý
# * Date  : 9. 6. 2015
# *
# *****************************************************************************

require_dependency "ric_user/public_controller"

module RicUser
	class PublicUsersController < PublicController
		include RicUser::Concerns::Controllers::Public::UsersController
	end
end

ric_user/app/controllers/ric_user/roles_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Roles
# *
# * Author: Matěj Outlý
# * Date  : 9. 6. 2015
# *
# *****************************************************************************

require_dependency "ric_user/application_controller"

module RicUser
	class RolesController < ApplicationController
		include RicUser::Concerns::Controllers::RolesController
	end
end

ric_user/app/controllers/ric_user/sessions_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Session
# *
# * Author: Matěj Outlý
# * Date  : 26. 11. 2015
# *
# *****************************************************************************

require_dependency "ric_user/application_controller"

module RicUser
	class SessionsController < ApplicationController
		include RicUser::Concerns::Controllers::SessionsController
	end
end

ric_user/app/controllers/ric_user/user_passwords_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * User passwords
# *
# * Author: Matěj Outlý
# * Date  : 9. 6. 2015
# *
# *****************************************************************************

require_dependency "ric_user/application_controller"

module RicUser
	class UserPasswordsController < ApplicationController
		include RicUser::Concerns::Controllers::UserPasswordsController
	end
end

ric_user/app/controllers/ric_user/users_controller.rb
# *****************************************************************************
# * Copyright (c) Clockstar s.r.o. All rights reserved.
# *****************************************************************************
# *
# * Users
# *
# * Author: Matěj Outlý
# * Date  : 9. 6. 2015
# *
# *****************************************************************************

require_dependency "ric_user/application_controller"

module RicUser
	class UsersController < ApplicationController
		include RicUser::Concerns::Controllers::UsersController
	end
end

ric_user/app/views/ric_user/users/_actions.html.erb
<%= rug_menu_for(@user, options.merge(path_base: "users")) do |m| %>
	<%= m.index_item %>
	<%= m.new_item t("headers.ric_user.users.new"), false, modal: "new_user_modal" %>
	<%= m.show_item %>
	<% if @user && !@user.new_record? %>
		<%= m.edit_item t("headers.ric_user.users.edit"), false, 
			modal: "edit_user_#{@user.id}_modal" 
		%>
		<%= m.edit_item t("headers.ric_user.user_passwords.edit"), false, 
			modal: "edit_user_password_#{@user.id}_modal", 
			icon: "lock" 
		%>
		<%= m.item t("headers.ric_user.user_passwords.regenerate"), regenerate_user_password_path(@user), 
			icon: "refresh", 
			method: :put 
		%>
		<%# if @user.locked? %>
			<%#= m.item t("headers.ric_user.users.unlock"), unlock_user_path(@user), 
				icon: "thumbs-up", 
				method: :put 
			%>
		<%# else %>
			<%#= m.item t("headers.ric_user.users.lock"), lock_user_path(@user), 
				icon: "thumbs-down", 
				method: :put 
			%>
		<%# end %>
	<% end %>
	<%= m.destroy_item %>
<% end %>

<%= rug_modal "new_user_modal" do |m| %>
	<%= m.header t("headers.ric_user.users.new") %>
	<%= render partial: "form", locals: {
		modal: m,
		user: RicUser.user_model.new
	} %>
<% end %>

<% if @user && !@user.new_record? %>
	<%= rug_modal "edit_user_#{@user.id}_modal" do |m| %>
		<%= m.header t("headers.ric_user.users.edit") %>
		<%= render partial: "form", locals: {
			modal: m,
			user: @user
		} %>
	<% end %>
	<%= rug_modal "edit_user_password_#{@user.id}_modal" do |m| %>
		<%= m.header t("headers.ric_user.user_passwords.edit") %>
		<%= render partial: "ric_user/user_passwords/form", locals: {
			modal: m,
			user: @user
		} %>
	<% end %>
<% end %>

ric_user/app/views/ric_user/users/_filters.html.erb
<% if action_name == "index" %>
	<%= rug_form_for(@filter_user, 
		url: ric_user.filter_users_path,
		html: { id: "filter_user" }
	) do |f| %>
		<div class="form-inline">
			<%= f.text_input_row :email, :text_field, label: false, placeholder: RicUser.user_model.human_attribute_name(:email) %>
			<%= f.primary_button_row :submit, label: t("helpers.submit.filter") %>
		</div>
	<% end %>
<% end %>

ric_user/app/views/ric_user/users/_form.html.erb
<%= rug_form_for(user, 
	create_path: :users_path, 
	update_path: :user_path,
	ajax: {
		success_message: RicUser.user_model.human_notice_message(user.new_record? ? :create : :update),
		error_message: RicUser.user_model.human_error_message(user.new_record? ? :create : :update),
		clear_on_submit: user.new_record?,
		on_success: {
			toggle_modal: { selector: "##{modal.id}" },
			reload_page: true
		}
	}
) do |f| %>
	<%= modal.body do %>
		<%= f.name_row :name if RicUser.user_name == true %>
		<%= f.text_input_row :email, :email_field %>
		<%#= f.picker_row :role if RicUser.user_model.has_role? %>
	<% end %>
	<%= modal.footer do %>
		<%= f.primary_button_row :submit %>
	<% end %>
<% end %>

ric_user/app/views/ric_user/users/_index.html.erb
<%= rug_index(users, options) do |t| %>
	<%= t.body do |b| %>
		<%= b.string :email, show: { path: :user_path }, sort: true %>
		<%= b.name :name, type: { strong_lastname: true } if RicUser.user_name == true %>
		<%#= b.enum :role if RicUser.user_model.has_role? %>
		<%#= b.enum_array :roles if RicUser.user_model.has_roles? %>
		<%= b.state :locked?, 
			action: { 
				path: -> (user) { user.locked? ? unlock_user_path(user) : lock_user_path(user) } ,
				method: :put
			}, 
			type: { use_translation: true } 
		%>
		<%= b.action :edit, modal: true do |m, user| %>
			<%= m.header t("headers.ric_user.users.edit") %>
			<%= render partial: "form", locals: {
				modal: m,
				table: t,
				user: user
			} %>
		<% end %>
		<%= b.action :edit_password, modal: true, style: :primary, icon: "lock" do |m, user| %>
			<%= m.header t("headers.ric_user.user_passwords.edit") %>
			<%= render partial: "ric_user/user_passwords/form", locals: {
				modal: m,
				table: t,
				user: user
			} %>
		<% end %>
		<%= b.action :regenerate_password, path: -> (user) { regenerate_user_password_path(user) }, 
			icon: "refresh", 
			method: :put,
			style: :primary
		%>
		<%= b.action :destroy, path: :user_path, ajax: true %>
	<% end %>
	<%= t.footer do |f| %>
		<%= f.pagination %>
		<%= f.summary %>
	<% end %>
<% end %>

ric_user/app/views/ric_user/users/index.html.erb
<%= rug_index(@users) do |t| %>
	<%= t.body do |b| %>
		<%= b.string :email, show: { path: :user_path }, sort: true %>
		<%= b.string :name_lastname, sort: true %>
		<%= b.string :name_firstname, sort: true %>
		<%#= b.enum :role if RicUser.user_model.has_role? %>
		<%#= b.enum_array :roles if RicUser.user_model.has_roles? %>
		<%= b.action :edit, path: :edit_user_path %>
		<%= b.action :destroy, path: :user_path %>
	<% end %>
	<%= t.footer do |f| %>
		<%= f.pagination %>
		<%= f.summary %>
	<% end %>
<% end %>

ric_user/app/views/ric_user/users/show.html.erb
<%= rug_show(@user) do |t| %>
	<%= t.body do |b| %>
		<%= b.name :name if RicUser.user_name == true %>
		<%= b.string :email %>
		<%#= b.enum :role if RicUser.user_model.has_role? %>
		<%#= b.enum_array :roles if RicUser.user_model.has_roles? %>
		<%= b.integer :sign_in_count %>
		<%= b.datetime :current_sign_in_at %>
		<%= b.state :locked?, 
			action: { 
				path: -> (user) { user.locked? ? unlock_user_path(user) : lock_user_path(user) } ,
				method: :put
			}, 
			type: { use_translation: true } 
		%>
	<% end %>
<% end %>